### ISSUE TITLE
BatchNormalization name change 

### ISSUE THREAD

**Issue by Aixile** [neka-nat/tensorboard-chainer#1]
BatchNormalizationFunction  has renamed to BatchNormalization in Chainer v3, which will cause importing error on Chainer v3

**Comment by neka-nat** [comment]
Hi, Aixile.
I prepared a branch for chainer3.
Please try using it.
https://github.com/neka-nat/tensorboard-chainer/tree/chainer3

**Comment by Aixile** [comment]
Thanks!
